import { StylesProvider } from './styles-provider'
import './globals.css'
import { QueryProvider } from 'app/provider/query/provider'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <StylesProvider>{children}</StylesProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
